function g = function_input_2d(X,Y,c,V,Sigma,the,xf,yr,yl)

A = (cos(the))^2 / Sigma(1,1) + (sin(the))^2 / Sigma(2,2);
B = (cos(the)*sin(the)) / Sigma(1,1) - (cos(the)*sin(the)) / Sigma(2,2);
C = (cos(the)*sin(the)) / Sigma(1,1) - (cos(the)*sin(the)) / Sigma(2,2);
D = (sin(the))^2 / Sigma(1,1) + (cos(the))^2 / Sigma(2,2);

g = 0;

g = V/sqrt((2*pi)^2*det(Sigma))*exp(-1/2*(A*(X-c(1)).^2 +...
    B*(X-c(1)).*(Y-c(2)) + C*(X - c(1)).*(Y - c(2)) + D*(Y-c(2)).^2));

g = g + V/sqrt((2*pi)^2*det(Sigma))*exp(-1/2*(A*(X-c(1)).^2 +...
    B*(X-c(1)).*(-(Y-(2*yl-c(2)))) + C*(X - c(1)).*(-(Y-(2*yl-c(2)))) +...
    D*(-(Y-(2*yl-c(2)))).^2));

g = g + V/sqrt((2*pi)^2*det(Sigma))*exp(-1/2*(A*(X-c(1)).^2 +...
    B*(X-c(1)).*(-(Y-(2*yr-c(2)))) + C*(X - c(1)).*(-(Y-(2*yr-c(2)))) +...
    D*(-(Y-(2*yr-c(2)))).^2));

g = g + V/sqrt((2*pi)^2*det(Sigma))*exp(-1/2*(A*(-(X-(2*xf-c(1)))).^2 +...
    B*(-(X-(2*xf-c(1)))).*(Y-c(2)) + C*(-(X-(2*xf-c(1)))).*(Y - c(2)) + D*(Y-c(2)).^2));

g = g + V/sqrt((2*pi)^2*det(Sigma))*exp(-1/2*(A*(-(X-(2*xf-c(1)))).^2 +...
    B*(-(X-(2*xf-c(1)))).*(-(Y-(2*yl-c(2)))) +...
    C*(-(X-(2*xf-c(1)))).*(-(Y-(2*yl-c(2)))) + D*(-(Y-(2*yl-c(2)))).^2));

g = g + V/sqrt((2*pi)^2*det(Sigma))*exp(-1/2*(A*(-(X-(2*xf-c(1)))).^2 +...
    B*(-(X-(2*xf-c(1)))).*(-(Y-(2*yr-c(2)))) +...
    C*(-(X-(2*xf-c(1)))).*(-(Y-(2*yr-c(2)))) + D*(-(Y-(2*yr-c(2)))).^2));
